#!/usr/bin/env python3

import click
import json
import os
from rich.console import Console

import math
import sys
import glob
import rich.traceback

from os.path import exists, join
from daqconf.core.conf_utils import make_app_command_data
from daqconf.core.config_file import generate_cli_from_schema
from daqconf.core.metadata import write_metadata_file
from daqconf.core.system import System
from hello import helloapp_gen

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

console = Console()

# Set moo schema search path
from dunedaq.env import get_moo_model_path
import moo.io
moo.io.default_load_path = get_moo_model_path()

CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])
@click.command(context_settings=CONTEXT_SETTINGS)
#@click.option('--name-string', default="Name", help='Name parameter for conversation')
#@click.option('--wait-ms', default=1000, help='Number of ms to wait between list sends')
@generate_cli_from_schema('hello/confgen.jsonnet', 'hello_gen')
@click.argument('json_dir', type=click.Path())
def cli(config, json_dir):#name_string, wait_ms

    if  exists(json_dir):#os.path.
        raise RuntimeError(f"Directory {json_dir} already exists")

    config_data = config[0]
    config_file = config[1]

    #console.log(f"\nTotal configuration for this app before any overrides: {config_data.pod()}")

    # Get our config objects
    # Loading this one another time... (first time in config_file.generate_cli_from_schema)    

    moo.otypes.load_types('hello/confgen.jsonnet')
    import dunedaq.hello.confgen as confgen
    moo.otypes.load_types('daqconf/confgen.jsonnet')
    import dunedaq.daqconf.confgen as daqconfgen

    console.log(f"\nIndividual configuration records before any command line overrides: ")
    from hello import helloapp_gen   

    # Copy-of-a-hack, see daqconf's daqconf_multiru_gen file (commit e26a21d54fc5)
    boot = daqconfgen.boot(**config_data.boot)
    console.log(f"boot configuration object: {boot.pod()}")

    hello = confgen.hello(**config_data.hello)
    console.log(f"hello configuration object: {hello.pod()}")

    console.log(f"\nIndividual configuration records after any command line overrides: ")
    console.log(f"boot configuration object: {boot.pod()}")
    console.log(f"hello configuration object: {hello.pod()}")	

    console.log("Loading helloapp config generator")
    
    the_system = System()
    
    the_system.apps["hello-app"] = helloapp_gen.get_hello_app(
        nickname = "the-solo-app", 
        name_parameter = hello.name_string,
        n_wait_ms = hello.wait_ms
    )

    ####################################################################                                  
    # Application command data generation                                                                 
    ####################################################################                                  

    # Arrange per-app command data into the format used by util.write_json_files()    

    app_command_datas = {
        name : make_app_command_data(the_system, app, name)
        for name, app in the_system.apps.items()
    }

    # Make boot.json config                                                                               
    from daqconf.core.conf_utils import make_system_command_datas, write_json_files
    system_command_datas = make_system_command_datas(boot, the_system, verbose = False)

    write_json_files(app_command_datas, system_command_datas, json_dir, verbose=True)

    console.log(f"hello app config generated in {json_dir}")

    write_metadata_file(json_dir, "hello_gen", config_file)

if __name__ == "__main__":
    try:
        cli(show_default=True, standalone_mode=True)
    except Exception:
        console.print_exception()
